[phases.setup]
nixPkgs = ["python310", "nodejs-18_x", "pip"]

[phases.install]
cmds = [
  "npm ci",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

