[phases.setup]
nixPkgs = ["python310Full", "nodejs-18_x"]

[phases.install]
cmds = [
  "npm ci",
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip setuptools wheel",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

