[phases.setup]
nixPkgs = ["python311Full", "nodejs-18_x"]

[phases.install]
cmds = [
  "npm ci",
  "python3 -m venv venv",
  ". venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

